[package]
name = "faith"
version = "0.1.0"
edition = "2024"
description = "fÃ¡ith: a Rust-powered JS fetch"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2", features = ["napi4", "tokio_rt"] }
napi-derive = "2"
reqwest = { version = "0.12", features = ["trust-dns", "json", "stream"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
jiff = "0.1"
bytes = "1"
thiserror = "1"

[build-dependencies]
napi-build = "2"

[dev-dependencies]
napi = { version = "2", features = ["napi4", "tokio_rt"] }
reqwest = { version = "0.12", features = ["trust-dns", "json", "stream"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1"
