[package]
name = "faith"
version = "0.0.0"
edition = "2024"
description = "fÃ¡ith: a Rust-powered JS fetch"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "3.6.1", features = ["napi4", "tokio_rt"] }
napi-derive = "3.4.0"
reqwest = { version = "0.12.24", features = ["trust-dns", "json", "stream"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["full"] }

[build-dependencies]
napi-build = "2.3.1"

[dev-dependencies]
reqwest = { version = "0.12.24", features = ["trust-dns", "json", "stream"] }
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["full"] }
