name: Build and publish
on:
  push:
    branches: ["main"]
    tags: ["v*.*.*"]
  pull_request:

env:
  DEBUG: "napi:*"
  MACOSX_DEPLOYMENT_TARGET: "10.13"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-apple-darwin
            flags: "-x"
          - target: aarch64-apple-darwin
            flags: "-x"
          - target: x86_64-pc-windows-msvc
            flags: "-x"
          - target: i686-pc-windows-msvc
            flags: "-x"
          - target: aarch64-pc-windows-msvc
            flags: "-x"
          - target: x86_64-unknown-linux-gnu
            flags: "--use-napi-cross"
          - target: aarch64-unknown-linux-gnu
            flags: "--use-napi-cross"
          - target: x86_64-unknown-linux-musl
            flags: "-x"
          - target: aarch64-unknown-linux-musl
            flags: "-x"
          - target: armv7-unknown-linux-gnueabihf
            flags: "--use-napi-cross"
          - target: powerpc64le-unknown-linux-gnu
            flags: "--use-napi-cross"
          - target: s390x-unknown-linux-gnu
            flags: "--use-napi-cross"
    runs-on: ubuntu-latest
    steps:
      - name: Free up space
        run: sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /usr/local/.ghcup || true
      - uses: actions/checkout@v6
      - name: Configure toolchain
        run: |
          rustup toolchain install --profile minimal --no-self-update stable
          rustup default stable
          rustup target add ${{ matrix.target }}
      - uses: Swatinem/rust-cache@v2
      - uses: actions/setup-node@v6
        with:
          node-version: "22"
          cache: npm
      - name: Install ziglang
        uses: mlugg/setup-zig@v2
        with:
          version: 0.14.1
      - name: Install cargo toolchains
        uses: taiki-e/install-action@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tool: cargo-zigbuild,cargo-xwin
      - run: npm install
      - run: npm run build --target ${{ matrix.target }} ${{ matrix.flags }}
        env:
          XWIN_CACHE_DIR: ${{ github.workspace }}/.xwin
      - uses: actions/upload-artifact@v5
        with:
          name: bindings-${{ matrix.target }}
          path: "*.node"
          if-no-files-found: error

  test-host:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-apple-darwin
            host: macos-latest
            architecture: x64
          - target: aarch64-apple-darwin
            host: macos-latest
            architecture: arm64
          - target: x86_64-pc-windows-msvc
            host: windows-latest
            architecture: x64
          - target: aarch64-pc-windows-msvc
            host: windows-11-arm
            architecture: arm64
          - target: i686-pc-windows-msvc
            host: windows-latest
            architecture: x64
    runs-on: ${{ matrix.host }}
    needs:
      - build
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "20"
          cache: npm
          architecture: ${{ matrix.architecture }}
      - name: Setup node x86
        if: matrix.target == 'i686-pc-windows-msvc'
        run: npm config set cpu ia32
        shell: bash
      - name: Install dependencies
        run: npm install
      - name: Setup node x86
        uses: actions/setup-node@v6
        if: matrix.target == 'i686-pc-windows-msvc'
        with:
          node-version: "20"
          cache: npm
          architecture: x86
      - name: Download bindings
        uses: actions/download-artifact@v6
        with:
          name: bindings-${{ matrix.target }}
          path: .
      - name: Run tests
        run: npm test:only

  test-docker:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            docker: node:20-slim
            args: ""
          - target: aarch64-unknown-linux-gnu
            docker: node:20-slim
            args: "--platform linux/arm64"
          - target: x86_64-unknown-linux-musl
            docker: node:20-alpine
            args: ""
          - target: aarch64-unknown-linux-musl
            docker: node:20-alpine
            args: "--platform linux/arm64"
          - target: armv7-unknown-linux-gnueabihf
            docker: node:20-bullseye-slim
            args: "--platform linux/arm/v7"
          - target: s390x-unknown-linux-gnu
            docker: node:20-slim
            args: "--platform linux/s390x"
          - target: powerpc64le-unknown-linux-gnu
            docker: node:20-slim
            args: "--platform linux/ppc64le"
    runs-on: ${{ contains(matrix.target, 'aarch64') && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    needs:
      - build
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "20"
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Download bindings
        uses: actions/download-artifact@v6
        with:
          name: bindings-${{ matrix.target }}
          path: .
      - name: Set up QEMU
        if: ${{ !contains(matrix.target, 'aarch64') }}
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64,arm
      - run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        if: ${{ !contains(matrix.target, 'aarch64') }}
      - name: Run tests
        uses: addnab/docker-run-action@v3
        # Node.js on qemu randomly segfaults on powerpc64le
        continue-on-error: ${{ matrix.target == 'powerpc64le-unknown-linux-gnu' }}
        with:
          image: ${{ matrix.docker }}
          options: ${{ matrix.args }} -v ${{ github.workspace }}:/build -w /build
          run: |
            set -e
            npm test:only

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs:
      - test-host
      - test-docker
    steps:
      - uses: actions/checkout@v6
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Download all artifacts
        uses: actions/download-artifact@v6
        with:
          path: artifacts
      - name: Move artifacts
        run: npx napi artifacts
      - name: List packages
        run: ls -R ./npm
      - name: Show package.json
        run: cat package.json
      - name: Publish
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          npm config set provenance true
          npm publish --access public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          # publishing new platform packages requires a token. generate a new 7d one for it!
