name: Test
env:
  DEBUG: napi:*
  APP_NAME: faith
  MACOSX_DEPLOYMENT_TARGET: "10.13"
  CARGO_INCREMENTAL: "1"
  CFLAGS_aarch64_unknown_linux_gnu: "-D__ARM_ARCH=8"
on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "LICENSE*"
      - "**/*.gitignore"
      - .editorconfig
      - .rustfmt.toml
      - docs/**
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        host:
          - macos-latest
          - windows-latest
          - ubuntu-latest
        nodejs:
          - 20
          - 22
          - 24
    name: stable - ${{ matrix.host }} - node@${{ matrix.nodejs }}
    runs-on: ${{ matrix.host }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.nodejs }}
          cache: npm
      - run: rustup toolchain install --profile minimal --no-self-update stable
      - uses: Swatinem/rust-cache@v2
      - run: npm install
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Start httpbin
        run: |
          go run github.com/mccutchen/go-httpbin/v2/cmd/go-httpbin@latest -host 127.0.0.1 -port 8888 &
          sleep 10
        shell: bash
      - run: npm run test
        env:
          HTTPBIN_URL: http://localhost:8888
